networks:
  mongodb_network:
    driver: bridge

services:
  # Configuration server
  configs1:
    container_name: configs1
    hostname: configs1
    image: mongo:8.0.4
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 1 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/configs1:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  configs2:
    container_name: configs2
    hostname: configs2
    image: mongo:8.0.4
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 1 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/configs2:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  configs3:
    container_name: configs3
    hostname: configs3
    image: mongo:8.0.4
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 1 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/configs3:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  # Shard servers
  shards1:
    container_name: shards1
    hostname: shards1
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards1:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards2:
    container_name: shards2
    hostname: shards2
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards2:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards3:
    container_name: shards3
    hostname: shards3
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards3:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards4:
    container_name: shards4
    hostname: shards4
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards4:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards5:
    container_name: shards5
    hostname: shards5
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards5:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards6:
    container_name: shards6
    hostname: shards6
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards6:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  shards7:
    container_name: shards7
    hostname: shards7
    image: mongo:8.0.4
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db --wiredTigerCacheSizeGB 12 --bind_ip_all
    volumes:
      - F:/Database/MongoDBCluster/shards7:/data/db
    networks:
      - mongodb_network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  # Mongos router
  mongos:
    container_name: mongos
    hostname: mongos
    image: mongo:8.0.4
    command: mongos --configdb configReplSet/configs1:27017,configs2:27017,configs3:27017 --bind_ip_all --port 27017
    ports:
      - 30000:27017
    networks:
      - mongodb_network
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: '0.5'
    depends_on:
      - configs1
      - configs2
      - configs3
      - shards1
      - shards2
      - shards3
      - shards4
      - shards5
      - shards6
      - shards7
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
